### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by CrazySliva** [N-Multifibra/netbox-proxbox#28]
Good afternoon, with the help of heavenly power, I managed to install the plugin. But it fails to start. When clicking on the Proxmox VM/СT link, an error occurs:
Server Error
The complete exception is provided below:
<class 'django.template.exceptions.TemplateDoesNotExist'>

base.html

Python version: 3.8.10
NetBox version: 3.0.3

------------

And another question, does the plugin support work with api on https or not?

**Comment by dyustepanov** [comment]
I have same error.

<class 'django.template.exceptions.TemplateDoesNotExist'>

base.html

Python version: 3.8.10
NetBox version: 3.0.6

**Comment by valireality** [comment]
<class 'django.template.exceptions.TemplateDoesNotExist'>

base.html

Python version: 3.8.10
NetBox version: 3.0.10

**Comment by ndom91** [comment]
This looks like its not updated for Netbox v3.0.0+ yet. Some template names have changed / changed how they're exported. Plugins will need to be updated :/

**Comment by topa-LE** [comment]
I have same error.

**Comment by skydiablo** [comment]
check it out: https://github.com/N-Multifibra/netbox-proxbox/pull/29

**Comment by emersonfelipesp** [comment]
@skydiablo pull request solved this issue. Thank you!
